apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-canary
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
